default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: developer_f
  password:  
  host: localhost

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

